apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inbox
  labels:
    role: inbox
    app: LocalEGA
spec:
  replicas: 1
  serviceName: inbox
  selector:
    matchLabels:
      app: inbox
  template:
    metadata:
      labels:
        app: inbox
        role: inbox
    spec:
      containers:
      - name: inbox
        image: nbisweden/ega-mina-inbox:latest
        imagePullPolicy: Always
        env:
        - name: BROKER_HOST
          value: mq.localega.svc.cluster.local
        - name: INBOX_PORT
          value: "2222"
        - name: CEGA_ENDPOINT
          value: http://cega-users/user/
        - name: CEGA_ENDPOINT_CREDS
          valueFrom:
            secretKeyRef:
              name: cega-creds
              key: credentials
        ports:
        - name: inbox
          containerPort: 2222
          protocol: TCP
        volumeMounts:
        - name: lega-inbox
          mountPath: /ega/inbox
      # restartPolicy: Always
      volumes:
      - name: lega-inbox
## select PVC or flexVolume
        persistentVolumeClaim:
          claimName: inbox-storage
##################################
#        flexVolume:
#          driver: ceph.rook.io/rook
#          fsType: ceph
#          options:
#            fsName: sharedfs
#            clusterNamespace: rook-ceph
#            path: /some/path/inside/cephfs
#            # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
#            # the path must exist on the filesystem, otherwise mounting the filesystem at that path will fail
