apiVersion: apps/v1
kind: Deployment
metadata:
  name: res-deploy
spec:
  replicas: 1
  strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
  selector:
        matchLabels:
          app: res-app
  template:
        metadata:
          labels:
            app: res-app
        spec:
          containers:
          - name: res
            image: <to add>
            imagePullPolicy: Always
            env:
            - name: CONFIG_SERVICE
              value: http://config.default.svc.cluster.local
            ports:
            - containerPort: 9090
            livenessProbe:
              tcpSocket:
                port: 9090
              initialDelaySeconds: 60
              periodSeconds: 60
            volumeMounts:
              - mountPath: "/log"
                name: log-directory
          volumes:
            - name: log-directory
              hostPath:
                path: /tmp/logs
