apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inbox-storage
spec:
  storageClassName: local #Change this to whatever going to be used in production.
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi #Make this bigger in production.
