apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapper
  labels:
    role: mapper
    app: LocalEGA
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapper
  template:
    metadata:
      labels:
        app: mapper
        role: mapper
    spec:
      containers:
      - name: mapper
        image: nbisweden/ega-base:latest
        imagePullPolicy: Always
        command: ["gosu", "lega", "ega-id-mapper"]
        volumeMounts:
        - name: mapper-conf
          mountPath: /etc/ega
      restartPolicy: Always
      volumes:
      - name: mapper-conf
        configMap:
          name: lega-config
          items:
            - key: conf.ini
              path: conf.ini
          defaultMode: 0744
